disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Shr3wd"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
author = { name = "Shr3wcl", email = "tripm2112@gmail.com", image = "img/profile.png", headline = "Just a boy who loves life", bio = "Love it like it loves me", links = [ { email = "mailto:tripm2112@gmail.com" }, { github = "https://github.com/shr3wcl" }, { x-twitter = "https://twitter.com/0xShr3wd" } ] }
logo = "no"
