colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = false
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
defaultBackgroundImage = "background.png"

[header]
    layout = "basic"

[footer]
    showMenu = true
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
    showScrollToTop = true

[homepage]
    layout = "background"
    showRecent = "enable"
    showRecentItems = "10"
    showMoreLink = true
    showMoreLinkDest = "/posts/"
    cardView = true
    cardViewScreenWidth = false
    layoutBackgroundBlur = true

[article]
    showDate = true
    showViews = false
    showLikes = false
    showDateOnlyInArticle = false
    showDateUpdated = false
    showAuthor = true
    showHero = true
    layoutBackgroundBlur = true
    layoutBackgroundHeaderSpace = true
    showBreadcrumbs = true
    showDraftLabel = true
    showEdit = false
    editAppendPath = true
    seriesOpened = true
    showHeadingAnchors = true
    showPagination = true
    invertPagination = false
    showReadingTime = true
    showTableOfContents = true
    showTaxonomies = true
    showAuthorsBadges = true
    showWordCount = true
    showZenMode = false
    heroStyle = "background"
    showRelatedContent = false

[list]
    showHero = true
    layoutBackgroundBlur = true
    layoutBackgroundHeaderSpace = true
    showBreadcrumbs = false
    showSummary = true
    showViews = false
    showLikes = false
    showTableOfContents = true
    showCards = true
    orderByWeight = false
    groupByYear = true
    cardView = true
    cardViewScreenWidth = false
    constrainItemsWidth = false
    heroStyle = "background"

[sitemap]
    excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
    showTermCount = true
    showHero = false
    showBreadcrumbs = false
    showViews = false
    showLikes = false
    showTableOfContents = false
    cardView = true

[term]
    showHero = false
    showBreadcrumbs = false
    showViews = false
    showLikes = false
    showTableOfContents = true
    groupByYear = false
    cardView = true
    cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]
